server:
  port: 8000

url:
  prefix: gulimall-product
  white-list: /logout

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.131.172:8848

  datasource:
    username: root
    password: Celi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.131.172/gulimall_pms?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      max-lifetime: 120000
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.atguigu.gulimall.product.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型
      id-type: ASSIGN_ID
    banner: false